[constants]
ndk_sysroot = '/usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/sysroot'
working_dir = '/home/runner/work/mesa-funnymdzz/mesa-funnymdzz'

[binaries]
c       = '/usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang'
cpp     = '/usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++'
ar      = '/usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'
strip   = '/usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip'
pkg-config = '/usr/bin/pkg-config'

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[properties]
needs_exe_wrapper = true

[built-in options]
c_args = [
    '--sysroot=' + ndk_sysroot,
    '-I' + working_dir + '/shims',
    '-D__TERMUX__',
    '-include', working_dir + '/src/util/u_gralloc/force_aosp_abi.h'
  ]
cpp_args = [
    '--sysroot=' + ndk_sysroot,
    '-I' + working_dir + '/shims',
    '-fno-exceptions',
    '-D__TERMUX__',
    '-include', working_dir + '/src/util/u_gralloc/force_aosp_abi.h'
  ]
c_link_args = [
    '-L/usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/18/lib/linux/aarch64',
    '-L' + working_dir + '/shims',
    '-llog',
    '-lsync',
    '-Wl,--allow-shlib-undefined',
    '-Wl,--unset-version'
  ]
cpp_link_args = [
    '-L/usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/18/lib/linux/aarch64',
    '-L' + working_dir + '/shims',
    '-llog',
    '-lsync',
    '-Wl,--allow-shlib-undefined',
    '-Wl,--unset-version'
  ]
